version: "3"
services:
  backend: docker-registry.if-lab.de/arme/spotitube-backend
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=PathPrefixStrip:/$CI_PROJECT_PATH_SLUG
        - traefik.port=8443
        - traefik.docker.network=proxy

networks:
  default:
    external: false
  proxy:
    external: true
