[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
secret_key = "leVIfmV/i+3lQM4JNanKXIex5Xl8BnwtomGXW4WOqPU="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers =  4
keep_alive = 5
log = "normal"
secret_key = "leVIfmV/i+3lQM4JNanKXIex5Xl8BnwtomGXW4WOqPU="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 443
workers = 6
keep_alive = 5
log = "critical"
secret_key = "aoQrXLvBiF2T467CV03YZrHGCfacLN8s0/1zoOGAAP8="
limits = { forms = 32768 }

[production.tls]
certs = "private/ca_cert.pem"
key = "private/ca_key.pem"
